[versions]
agp = "8.3.2"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
glide = "4.16.0"
kotlin = "1.9.20"
leanback = "1.0.0"
rxandroid = "3.0.0"
rxjava = "3.0.6"
threetenabp = "1.3.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

